---
# Install k3s service files for all servers
- name: Install k3s service for all servers
  ansible.builtin.include_role:
    name: systemd_helper
  vars:
    target_hostname: "{{ hostvars[item].hostname }}"
    service_name: "k3s"
    service_content: "{{ lookup('template', '../k3s_common/templates/k3s.service.j2') }}"
  loop: "{{ groups['pi_servers'] | default([]) }}"
  loop_control:
    label: "{{ hostvars[item].hostname }}"

# Install firstboot-ops service for all servers
- name: Install firstboot-ops service
  ansible.builtin.include_role:
    name: systemd_helper
  vars:
    target_hostname: "{{ hostvars[item].hostname }}"
    service_name: "firstboot-ops"
    service_content: "{{ lookup('template','firstboot-ops.service.j2') }}"
  loop: "{{ groups['pi_servers'] | default([]) }}"
  loop_control:
    label: "{{ hostvars[item].hostname }}"
