---
# Install k3s-server service files
- name: Install k3s-server unit for pi01 (cluster-init)
  ansible.builtin.include_role:
    name: systemd_helper
  vars:
    target_hostname: "{{ hostvars[groups['pi_servers'][0]].hostname }}"
    service_name: "k3s-server"
    service_content: "{{ lookup('template','k3s-server.service.first.j2') }}"

- name: Install k3s-server unit for joining servers
  ansible.builtin.include_role:
    name: systemd_helper
  vars:
    target_hostname: "{{ hostvars[item].hostname }}"
    service_name: "k3s-server"
    service_content: "{{ lookup('template','k3s-server.service.join.j2') }}"
  loop: "{{ groups['pi_servers'] | difference([groups['pi_servers'][0]]) }}"
  loop_control:
    label: "{{ hostvars[item].hostname }}"

# Install firstboot-ops service for all servers
- name: Install firstboot-ops service
  ansible.builtin.include_role:
    name: systemd_helper
  vars:
    target_hostname: "{{ hostvars[item].hostname }}"
    service_name: "firstboot-ops"
    service_content: "{{ lookup('template','firstboot-ops.service.j2') }}"
  loop: "{{ groups['pi_servers'] | default([]) }}"
  loop_control:
    label: "{{ hostvars[item].hostname }}"
