---
- name: restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
  become: true

- name: restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  become: true