- name: Ensure rsync is installed
  ansible.builtin.package:
    name: rsync
    state: present
  become: true

- name: Ensure TFTP root exists
  ansible.builtin.file:
    path: /srv/tftp
    state: directory
    mode: "0755"
  become: true

- name: Sync /boot files to TFTP root (local on nas-vm, via sudo)
  ansible.builtin.command: >
    rsync -a --delete
    --out-format='<<CHANGED>>%i %n%L'
    /srv/rpi-build/firmware-master/boot/
    /srv/tftp/
  register: rsync_result
  changed_when: "'<<CHANGED>>' in rsync_result.stdout"
  become: true
