---
- name: Deploy MinIO using k8s_deployment_manager
  ansible.builtin.include_role:
    name: k8s_deployment_manager
  vars:
    deployment_name: "minio"
    deployment_namespace: "minio-system"
    manifests:
      - name: "minio-deployment"
        content: "{{ lookup('template', 'minio-deployment.yaml.j2') }}"
      - name: "minio-service"
        content: "{{ lookup('template', 'minio-service.yaml.j2') }}"
    depends_on_service: "k3s.service"
