---
- name: Prepare ArgoCD application manifests
  set_fact:
    argocd_manifests: "{{ argocd_manifests | default([]) + [{'name': item.name + '-app', 'content': lookup('template', 'argocd-application.yaml.j2')}] }}"
  loop: "{{ argocd_applications | default([]) }}"

- name: Add GitHub secret manifest if token is defined
  set_fact:
    argocd_manifests: "{{ argocd_manifests + [{'name': 'github-repo-secret', 'content': lookup('template', 'github-repo-secret.yaml.j2')}] }}"
  when: github_token is defined

- name: Deploy ArgoCD apps using k8s_deployment_manager
  ansible.builtin.include_role:
    name: k8s_deployment_manager
  vars:
    deployment_name: "argocd-apps"
    deployment_namespace: "argocd"
    manifests: "{{ argocd_manifests | default([]) }}"
    install_script_content: "{{ lookup('template', 'configure-argocd.sh.j2') | regex_replace('^#!/bin/bash.*?echo \\\".*\\\"', '') | regex_replace('echo \\\".*complete\\\"$', '') }}"
    depends_on_service: "firstboot-ops.service"
