---
- name: Create ArgoCD applications directory
  file:
    path: "{{ per_node_root_base }}/pi01/tmp/argocd-apps"
    state: directory
    mode: '0755'
  become: true

- name: Generate ArgoCD application manifests
  template:
    src: argocd-application.yaml.j2
    dest: "{{ per_node_root_base }}/pi01/tmp/argocd-apps/{{ item.name }}-app.yaml"
    mode: '0644'
  loop: "{{ argocd_applications | default([]) }}"
  become: true

- name: Create GitHub repository secret template
  template:
    src: github-repo-secret.yaml.j2
    dest: "{{ per_node_root_base }}/pi01/tmp/argocd-apps/github-repo-secret.yaml"
    mode: '0644'
  become: true
  when: github_token is defined

- name: Create ArgoCD configuration script
  template:
    src: configure-argocd.sh.j2
    dest: "{{ per_node_root_base }}/pi01/tmp/configure-argocd.sh"
    mode: '0755'
  become: true

- name: Create ArgoCD configuration systemd service
  copy:
    dest: "{{ per_node_root_base }}/pi01/etc/systemd/system/argocd-config.service"
    content: |
      [Unit]
      Description=Configure ArgoCD Applications
      After=firstboot-ops.service
      Requires=firstboot-ops.service

      [Service]
      Type=oneshot
      ExecStart=/tmp/configure-argocd.sh
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  become: true

- name: Enable ArgoCD configuration service
  file:
    src: ../argocd-config.service
    dest: "{{ per_node_root_base }}/pi01/etc/systemd/system/multi-user.target.wants/argocd-config.service"
    state: link
  become: true
