---
# Install k3s-agent service using systemd_helper
- name: Install k3s-agent service
  ansible.builtin.include_role:
    name: systemd_helper
  vars:
    target_hostname: "{{ hostvars[item].hostname }}"
    service_name: "k3s-agent"
    service_content: "{{ lookup('template','k3s-agent.service.j2') }}"
  loop: "{{ groups['pi_agents'] | default([]) }}"
  loop_control:
    label: "{{ hostvars[item].hostname }}"
