---
- name: Deploy KubeRay using k8s_deployment_manager
  ansible.builtin.include_role:
    name: k8s_deployment_manager
  vars:
    deployment_name: "kuberay"
    manifests:
      - name: "kuberay-operator"
        content: "{{ lookup('template', 'kuberay-operator.yaml.j2') }}"
    install_script_content: "{{ lookup('template', 'install-kuberay-operator.sh.j2') | regex_replace('^#!/bin/bash.*?echo \"Installing.*?\"', '') | regex_replace('echo \".*installation complete\"$', '') }}"
    depends_on_service: "firstboot-ops.service"
