---
- name: Create KubeRay manifests directory
  file:
    path: "{{ per_node_root_base }}/pi01/tmp/kuberay"
    state: directory
    mode: '0755'
  become: true

- name: Create KubeRay operator manifest
  template:
    src: kuberay-operator.yaml.j2
    dest: "{{ per_node_root_base }}/pi01/tmp/kuberay/kuberay-operator.yaml"
    mode: '0644'
  become: true

- name: Create KubeRay operator installation script
  template:
    src: install-kuberay-operator.sh.j2
    dest: "{{ per_node_root_base }}/pi01/tmp/install-kuberay-operator.sh"
    mode: '0755'
  become: true

- name: Create KubeRay operator systemd service
  copy:
    dest: "{{ per_node_root_base }}/pi01/etc/systemd/system/kuberay-operator-install.service"
    content: |
      [Unit]
      Description=Install KubeRay Operator
      After=firstboot-ops.service
      Requires=firstboot-ops.service

      [Service]
      Type=oneshot
      ExecStart=/tmp/install-kuberay-operator.sh
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  become: true

- name: Enable KubeRay operator installation service
  file:
    src: ../kuberay-operator-install.service
    dest: "{{ per_node_root_base }}/pi01/etc/systemd/system/multi-user.target.wants/kuberay-operator-install.service"
    state: link
  become: true
