# Network Configuration
net_iface: ens3
lan_cidr: 192.168.1.0/24
router_ip: 192.168.1.1
dns_servers: 192.168.1.1,50.116.35.168
dhcp_start: 192.168.1.51
dhcp_end: 192.168.1.150

# NAS Configuration
nas_ip: 192.168.1.197
nas_export_path: /volume2/nfsroot
local_nas_mount: /mnt/nfsroot
per_node_root_base: "{{ local_nas_mount }}/roots"

# Build Configuration
tftp_root: /srv/tftp
work_dir: /srv/rpi-build
raspios_url: "https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz"

# K3s Configuration
k3s_version: v1.29.7+k3s1
cluster_token: "{{ secrets.cluster_token | default('CHANGE_ME_TO_A_RANDOM_LONG_STRING') }}"
cluster_cidr: 10.42.0.0/16
service_cidr: 10.43.0.0/16

# Pi Configuration
tmpfs_var_log_size: 64m
tmpfs_tmp_size: 256m

pi_default_labels:
  role: worker
  arch: arm64

gpu_node_hostname: gpu01
gpu_taint: "gpu=true:NoSchedule"

# MinIO S3 Gateway Configuration
minio_root_user: "{{ secrets.minio_root_user | default('admin') }}"
minio_root_password: "{{ secrets.minio_root_password | default('change-me') }}"
minio_nfs_path: "/volume1/s3-data"
minio_service_type: "NodePort"

# ArgoCD Configuration
argocd_admin_password: "{{ secrets.argocd_admin_password | default('change-me') }}"
create_argocd_nodeport: true
github_username: "{{ secrets.github_username | default('') }}"
github_token: "{{ secrets.github_token | default('') }}"
docker_registry_secret: "{{ secrets.docker_registry_secret | default({}) }}"

# ArgoCD App of Apps Configuration
# This allows you to manage all cluster components via Git instead of Ansible
argocd_apps_repo_url: "{{ secrets.argocd_apps_repo_url | default('https://github.com/your-username/argocd-apps.git') }}"
argocd_apps_repo_branch: "{{ secrets.argocd_apps_repo_branch | default('main') }}"
argocd_apps_repo_path: "{{ secrets.argocd_apps_repo_path | default('.') }}"

# App of Apps - Single application that manages all others from Git
argocd_applications:
  - name: app-of-apps
    repo_url: "{{ argocd_apps_repo_url }}"
    branch: "{{ argocd_apps_repo_branch }}"
    path: "{{ argocd_apps_repo_path }}"
    namespace: argocd
    auto_sync: true
    auto_prune: true
    sync_options:
      - CreateNamespace=true
    # This application will discover and deploy other applications, operators, and infrastructure
    directory_recurse: true
