net_iface: eth0
lan_cidr: 192.168.1.0/24
router_ip: 192.168.1.1
dns_servers: 192.168.1.1,50.116.35.168
dhcp_start: 192.168.1.51
dhcp_end: 192.168.1.150

nas_ip: 192.168.1.197
nas_export_path: /volume2/nfsroot
local_nas_mount: /mnt/nfsroot
per_node_root_base: "{{ local_nas_mount }}/roots"

tftp_root: /srv/tftp
work_dir: /srv/rpi-build
raspios_url: "https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz"

# MinIO S3 Gateway Configuration
minio_root_user: "admin"
minio_root_password: "your-secure-password-here"
minio_nfs_path: "/volume1/s3-data"  # Adjust to your Synology share path
minio_service_type: "NodePort"  # Use NodePort for external access, ClusterIP for internal only

# ArgoCD Configuration
argocd_admin_password: "your-argocd-admin-password"
create_argocd_nodeport: true
github_username: "your-github-username"
github_token: "your-github-personal-access-token"  # For private repos

# Your Applications - Update these with your actual repos
argocd_applications:
  - name: my-web-app
    repo_url: https://github.com/your-username/your-web-app.git
    branch: main
    path: k8s
    namespace: web-apps
    auto_sync: true
    auto_prune: true
  - name: my-api
    repo_url: https://github.com/your-username/your-api.git
    branch: main
    path: deploy
    namespace: api
    auto_sync: true
    auto_prune: true

# KubeRay Configuration
ray_cluster_name: "pi-ray-cluster"
ray_namespace: "ray"
ray_head_cpu: "1"      # Adjust based on Pi resources
ray_head_memory: "2G"  # Adjust based on Pi resources
ray_worker_replicas: 3
ray_worker_cpu: "500m"
ray_worker_memory: "1G"
ray_dashboard_nodeport: 30265
ray_client_nodeport: 30001
ray_serve_nodeport: 30800

# GPU Ray Workers Configuration
ray_enable_gpu: true
ray_gpu_worker_replicas: 1
ray_gpu_worker_cpu: "2"      # Adjust based on GPU node resources
ray_gpu_worker_memory: "4G"  # Adjust based on GPU node resources
ray_gpus_per_worker: "1"
k3s_version: v1.29.7+k3s1
cluster_token: "CHANGE_ME_TO_A_RANDOM_LONG_STRING"
cluster_cidr: 10.42.0.0/16
service_cidr: 10.43.0.0/16

tmpfs_var_log_size: 64m
tmpfs_tmp_size: 256m

pi_default_labels:
  role: worker
  arch: arm64

gpu_node_hostname: gpu01
gpu_taint: "gpu=true:NoSchedule"
